const fs = require('fs');

const part2b = [
  'async function handleDelete(req, res, decoded) {',
  '  try {',
  '    const { courseId } = req.body || {};',
  '    if (!courseId) return res.status(400).json({ error: "Course ID is required." });',
  '    const courseRef = db.collection("courses").doc(courseId);',
  '    const courseSnap = await courseRef.get();',
  '    if (!courseSnap.exists) return res.status(404).json({ error: "Course not found." });',
  '    if (courseSnap.data().repUid !== decoded.uid) return res.status(403).json({ error: "Only the rep can delete." });',
  '    const subs = ["members","session","attendance","checkins","deviceFlags","absentFlags","manualRequests","hotspotLog","removalLog","exemptions","exemptionReasons","securityEvents","notifications"];',
  '    for (const sub of subs) {',
  '      try {',
  '        let snap = await courseRef.collection(sub).limit(500).get();',
  '        while (!snap.empty) {',
  '          const batch = db.batch();',
  '          snap.docs.forEach((d) => batch.delete(d.ref));',
  '          await batch.commit();',
  '          snap = await courseRef.collection(sub).limit(500).get();',
  '        }',
  '      } catch (err) { console.warn("Sub " + sub + ":", err.message); }',
  '    }',
  '    await courseRef.delete();',
  '    return res.status(200).json({ success: true, message: "Course deleted." });',
  '  } catch (error) {',
  '    console.error("Delete error:", error);',
  '    return res.status(500).json({ error: "Delete failed: " + error.message });',
  '  }',
  '}',
  '',
  'module.exports = async (req, res) => {',
  '  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });',
  '  try {',
  '    await verifyAppCheck(req);',
  '    const header = req.headers.authorization || "";',
  '    if (!header.startsWith("Bearer ")) return res.status(401).json({ error: "Unauthorized" });',
  '    const decoded = await getAuth().verifyIdToken(header.slice(7));',
  '    switch (req.query.action) {',
  '      case "enroll": return handleEnroll(req, res, decoded);',
  '      case "leave": return handleLeave(req, res, decoded);',
  '      case "remove": return handleRemove(req, res, decoded);',
  '      case "delete": return handleDelete(req, res, decoded);',
  '      default: return res.status(400).json({ error: "Invalid action" });',
  '    }',
  '  } catch (error) {',
  '    console.error("Course API error:", error);',
  '    return res.status(500).json({ error: "Server error" });',
  '  }',
  '};',
  '',
];

let existing = fs.readFileSync('api/course.js', 'utf8');
fs.writeFileSync('api/course.js', existing + '\n' + part2b.join('\n'));
console.log('Part 2b appended');
